### ISSUE TITLE
attempting to add resource pack profiles to immutable list

### ISSUE THREAD

**Issue by Linguardium** [EvergoodTeam/Chassis#2] opened 2022-07-22 02:02 UTC
Chassis 1.2.0

rest of info in log: 
https://mclo.gs/ReSu9J3

**Comment by Librv** [comment] 2022-07-28 09:39
Sorry for the late reply, could you also share the crash report? Should be located in the `crash-reports` directory.

**Comment by Librv** [comment] 2022-07-28 11:54
Sorry for the late reply! I can't reproduce the issue with Chassis and Compressor being the only mods loaded, so it would be very helpful if you could provide a download link for the modpack with which you're experiencing the crash.

Edit: found a modpack to reproduce the issue with, working on a fix.

**Comment by Librv** [comment] 2022-07-28 13:53
Not encountering the issue after 6b923b28eeb3ea6fb03972ff371a066e36a6f16e, closing. Official releases will be updated alongside the 1.19.1 release.

**Closed as completed by Librv** 2022-07-28 13:53 UTC
